version: '3.8'

services:
  postgres-db:
    image: postgres:17
    container_name: postgres-db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=teste
      - POSTGRES_USER=teste
      - POSTGRES_DB=testedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U teste -d testedb"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo-db:
    image: mongo:7.0.23
    container_name: mongo-db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=teste
      - MONGO_INITDB_ROOT_PASSWORD=teste
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/admin -u teste -p teste --quiet
      interval: 5s
      timeout: 5s
      retries: 5

  sysbench-runner:
    build:
      context: ./sysbench
    container_name: sysbench-runner
    depends_on:
      postgres-db:
        condition: service_healthy
    command: tail -f /dev/null

  ycsb-runner:
    build:
      context: ./ycsb
    container_name: ycsb-runner
    depends_on:
      mongo-db:
        condition: service_healthy
    command: tail -f /dev/null

volumes:
  postgres_data:
  mongo_data:

